fastlane_version "2.62.1"

default_platform :ios

platform :ios do

  desc 'build for testing'
  lane :build_for_testing do
    scan(
      build_for_testing: true,
      scheme: 'Bluepill-Sample',
      destination: 'platform=iOS Simulator,name=iPhone 6,OS=latest',
      derived_data_path: './build'
    )
  end

  lane :test_with_bluepill do
    sh('bluepill --config ../bluepill_config.json')
  end
end
